<?php defined('BASEPATH') OR exit('No direct script access allowed');

$config["icon_view"]        	= '<i class="material-icons">visibility</i>';
$config["icon_edit"]        	= '<i class="material-icons">edit</i>';
$config["icon_active"]      	= '<i class="material-icons">check</i>'; 
$config["icon_inactive"]      	= '<i class="material-icons">block</i>'; 
$config["icon_delete"]      	= '<i class="material-icons">delete_forever</i>'; 
$config["grid_open"] 			= '<div class="body">';
$config["grid_close"] 			= '</div> ';
$config["grid_size_open"] 		= '<div>';
$config["grid_size_close"] 		= '</div> ';
$config["grid_table_open"] 		= '<table class="table table-responsive table-condensed table-striped table-hover grid_datatable dataTable">';
$config["grid_table_close"] 	= '</table> ';
$config["url_action_view"]		= '';
$config["url_action_edit"]		= '';
$config["fgfield"]				= 'fgstatus';
$config["field_active"]			= '<i class="material-icons text-success">check_circle</i>';
$config["field_inactive"]		= '<i class="material-icons text-danger">cancel</i>';
$config["show_action_view"]		= true;
$config["show_action_edit"]		= true;
$config["show_action_delete"]	= true;
$config["show_action_column"]	= true;